마이페이지 수정 관련 리팩토링
With-Pet-Project/With-Pet-BE pull request #31
Opened 2023-02-11 14:48 UTC by Lee-Sang-Min1998

## 📌 관련 이슈

## ✨ 추가된 내용

mypage관련 controller,service 위치 따로 뺌

## 📚 논의사항

2023-02-11 15:13 UTC, Jin409 requested changes

2023-02-11 15:13 UTC, Jin409 commented on src/main/java/WebProject/withpet/users/controller/MypageController.java
> +@RequiredArgsConstructor
```java
@RequestMapping("/mypage")
```
가 낫지 않을까요?

2023-02-12 04:05 UTC, Lee-Sang-Min1998 commented on src/main/java/WebProject/withpet/users/controller/MypageController.java
> +@RequiredArgsConstructor
그 부분 바꿀려고 했었는데 깜빡했었네요 다음 pr때 수정해서 올릴게요~

2023-02-12 04:42 UTC, Jin409 commented on src/main/java/WebProject/withpet/users/controller/MypageController.java
> +@RequiredArgsConstructor
지금 수정하셔서 이 브랜치에 푸쉬하시면 돼요~

2023-02-12 13:21 UTC, closed without merging