이미지 업로드와 URL반환을 위한 설정 및 service 작성
With-Pet-Project/With-Pet-BE pull request #46
Opened 2023-02-21 16:20 UTC by Lee-Sang-Min1998

## 📌 관련 이슈

pull를 못하고 작성해서인지 브랜치가 꼬여서인지 다른 브랜치에 커밋한 내용까지 커밋되어 있습니다 ㅠㅠ 죄송해요.. 양이 상당하네요 

## ✨ 추가된 내용

1. S3에 이미지 업로드를 위한 build.gradle에 AWS 클라우드 의존성 추가와 validator 인터페이스 구현을 위한 의존성 추가
2. 게시글 생성 유효성 검증에서 validator 인터페이스 구현을 통한 검증 추가
3. 게시글 생성과 상세조회 service 추가
4. 이미지 엔티티와 게시글 엔티티 사이의 연관관계 편의 메소드 생성
5. 게시글 생성 및 상세조회 요청.응답 dto 생성
7. Article Custom 인터페이스 생성 및 구현체 생성
8. 확정성을 위해 apiErrorResponse.setCustomFieldErrors메소드에서 인자를 BindingResult에서 Error로 변경
9. 게시글 생성 예외처리 추가
10. S3에 이미지 업로드를 위한 AWS 설정 클래스 추가
11. AWS S3에 이미지를 업로드하고 해당 이미지의 URL를 반환하는 로직 구현

## 📚 논의사항

AwsS3Service와 AWSConfig파일 위치가 적절한지?

2023-02-22 13:45 UTC, Jin409 requested changes
수고하셨어요!

2023-02-22 13:45 UTC, Jin409 commented on src/main/java/WebProject/withpet/articles/Validation/ArticleValidator.java
> +                errors.rejectValue("place2", "INVALID_PARAMETER", "해당 태그에서 장소1은 필수 값");
위처럼 에러 메시지를 ~ 입니다로 통일하는게 어떨까요?

2023-02-22 13:45 UTC, Jin409 commented on build.gradle
> +	implementation group: 'org.springframework.boot', name: 'spring-boot-starter-validation', version: '2.5.6'
이거 이미 있을거에요..! 위에 있어요!
```java
implementation 'org.springframework.boot:spring-boot-starter-validation'
```

+ feat 보다 chore 쪽이 나을 것 같아요!

2023-02-22 13:45 UTC, Jin409 commented on src/main/java/WebProject/withpet/common/exception/GlobalExceptionHandler.java
> +            e.getErrors());
ArticleCreateException 에 남긴 리뷰와 동일합니다!

2023-02-22 13:45 UTC, Jin409 commented on src/main/java/WebProject/withpet/common/file/AwsS3Service.java
> +    }
이 메서드는 어떤 경우에 쓰이는 건가요?

2023-02-22 13:45 UTC, Jin409 commented on src/main/java/WebProject/withpet/articles/domain/Article.java
> +        String detailText) {
이렇게 되면, 댓글이 작성되고 삭제 될 때마다 article 에도 접근해서 값을 바꿔주고 저장해야 하니 쿼리가 낭비이지 않을까 싶은데 어떻게 생각하시나요?
만약 저라면, dto 단에만 commentCnt 를 두고 article 과 댓글을 반환할 때에 몇개인지 count 해서 보낼 것 같아요..! 이 상황도 고려해보셨는데 안된다고 판단하신 걸까요?

2023-02-22 13:45 UTC, Jin409 commented on src/main/java/WebProject/withpet/articles/controller/ArticleController.java
> +        ApiResponse response = new ApiResponse<>(200, "게시물 상세 조회 성공",
메시지는 ~ 습니다 ~ 입니다로 통일하는 것 어떨까요?

2023-02-22 16:22 UTC, Lee-Sang-Min1998 commented on src/main/java/WebProject/withpet/common/exception/ArticleCreateException.java
> +}
해당 에러는 게시글 생성에서 validator 인터페이스를 구현한 구현체에서 발생한 에러를 의미하는 목적으로 만들었습니다. Bean validation을 사용하면 MethodArgumentNotValidException같은 범용적인 에러로 처리가 가능한데 커스텀하게 구현한 유효성 검증에서는 에러를 터트릴 방법이 생각이 나지 않아서 해당 에러를 만들었습니다. 혹시 나은 방법이 있을까요?ㅠㅠ

2023-02-22 16:23 UTC, Lee-Sang-Min1998 commented on build.gradle
> +	implementation group: 'org.springframework.boot', name: 'spring-boot-starter-validation', version: '2.5.6'
넵 수정하겠습니다.

2023-02-22 16:28 UTC, Lee-Sang-Min1998 commented on src/main/java/WebProject/withpet/common/file/AwsS3Service.java
> +    }
파일을 S3에 보낼때 파일 이름이 필요한데 파일 이름을 생성할때 필요합니다. uploadImg 메소드에서 사용됩니당.

2023-02-22 16:32 UTC, Lee-Sang-Min1998 commented on src/main/java/WebProject/withpet/articles/domain/Article.java
> +        String detailText) {
현재 댓글 구현을 안 해서 해당 부분까지는 생각을 하지 못했습니다. 승희님 말씀대로 update 쿼리 안 날려서 좋을 것 같아서 우선 저렇게 수정하고 해당 api 구현 단계에서 어려움이 있으면 말씀드리겠습니다.

2023-02-22 16:33 UTC, Lee-Sang-Min1998 commented on src/main/java/WebProject/withpet/articles/controller/ArticleController.java
> +        ApiResponse response = new ApiResponse<>(200, "게시물 상세 조회 성공",
넵넵 수정할게여

2023-02-23 04:49 UTC, Jin409 requested changes
메인 브랜치에도 key 노출이 되어버려서 악용될 수 있으니 key 를 다시 발급받고 이후부터는 푸쉬하시면 안될 것 같습니다..! 배포 서버의 application.properties 에 있으니까 @Value 로 가져오기만 하면 될 것 같아요

2023-02-23 04:49 UTC, Jin409 commented on src/main/java/WebProject/withpet/users/service/UserSocialService.java
> +        body.add("redirect_uri", "http://localhost:3000/login/oauth/callback");
이 키 이렇게 노출해도 되는건가요?

2023-02-23 04:49 UTC, Jin409 commented on src/main/resources/application-API-KEY.properties
> +social-key=b52140c9061cc85f0ff31b4d548e998d
이렇게 하면 노출된거에요 ㅠㅠ.. 이렇게 노출되면 안됩니다..!

2023-02-23 04:49 UTC, Jin409 commented on src/main/resources/application-API-KEY.properties
> +social-key=b52140c9061cc85f0ff31b4d548e998d
해당 파일 삭제하고 다시 푸쉬해주세요!

2023-02-23 06:16 UTC, Jin409 commented on src/main/java/WebProject/withpet/common/exception/ArticleCreateException.java
> +}
article controller 의 아래 부분에서
```java
        if (errors.hasErrors()) {
            throw new ArticleCreateException(ErrorCode.INVALID_PARAMETER, errors);
        } else {
            articleService.createArticle(principalDetails.getUser(), request, images);
        }
```
ArticleCreateException 이 아니라 더 범용적인 에러를 터뜨리면 되지 않을까요?!

2023-02-23 13:50 UTC, Lee-Sang-Min1998 commented on src/main/java/WebProject/withpet/common/exception/ArticleCreateException.java
> +}
음.. 그냥 MethodArgumentNotValidException 터트려도 되겠네요 이렇게 수정해 볼게여

2023-02-23 13:53 UTC, merged